export const GET_COLLECTIONS_REQUEST = 'GET_ALL_COLLECTIONS_REQUEST';

export const GET_COLLECTIONS_SUCCESS = 'GET_COLLECTIONS_SUCCESS';
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS';

export const GET_COLLECTIONS_FAILURE = 'GET_ALL_COLLECTIONS_FAILURE';