// // Users
// export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
// export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
// export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
//
// // Widgets
// export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
// export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';
//
// // Search Layout
// export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

export const GET_ALL_COLLECTIONS_REQUEST = 'GET_ALL_COLLECTIONS_REQUEST';
export const GET_ALL_COLLECTIONS_SUCCESS = 'GET_ALL_COLLECTIONS_SUCCESS';
export const GET_ALL_COLLECTIONS_FAILURE = 'GET_ALL_COLLECTIONS_FAILURE';

export const GET_COLLECTION_REQUEST = "GET_COLLECTION_REQUEST";
export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS";
export const GET_COLLECTION_FAILURE = "GET_COLLECTION_FAILURE";