export const COLLECTIONS_STATE_REQUEST = 'COLLECTIONS_STATE_REQUEST';
export const COLLECTIONS_STATE_SUCCESS = 'COLLECTIONS_STATE_SUCCESS';
export const COLLECTIONS_STATE_FAILURE = 'COLLECTIONS_STATE_FAILURE';