export const COLLECTION_STATE_REQUEST = 'COLLECTION_STATE_REQUEST';
export const COLLECTION_STATE_SUCCESS = 'COLLECTION_STATE_SUCCESS';
export const COLLECTION_STATE_FAILURE = 'COLLECTION_STATE_FAILURE';